### ISSUE TITLE
AST: Support `accessor` with no decorator

### ISSUE THREAD

**Issue by Hawmex** [pabloalmunia/javacriptdecorators#1]
Looks like AST & transpiler don't support this:
```js
class C {
  accessor a = 1;
}

let c = new C();

console.log(c.a);
```
Error: `{"Error": Unexpected token (2:11)}`

**Comment by pabloalmunia** [comment]
Thansk @Hawmex, It's an error. The AST has support to decorator + accessor, but not for accessor only. We are working to fix this problem...

**Comment by pabloalmunia** [comment]
Hi @Hawmex, we are complete the support to accesor keyword. Now, the accessor is parse to the AST and transpiled to JS.

https://link.javascriptdecorators.org/H36msr

Please, confirm this new feature.

**Comment by Hawmex** [comment]
Thanks @pabloalmunia . `accessor` is parsed as expected. Closing the issue.
