### ISSUE TITLE
Transpiles `accessor static` instead of `static accessor`

### ISSUE THREAD

**Issue by Hawmex** [pabloalmunia/javacriptdecorators#2]
Code that currently works:
```js
class A {
  accessor static x = 1;
}
```

Expected code to work:
```js
class A {
  static accessor x = 1;
}
```

**Comment by pabloalmunia** [comment]
I have consulted the proposed specification and you are right, the keyword use is:

```
accessor ClassElementName[?Yield, ?Await] Initializer[+In, ?Yield, ?Await]?
```

We will change this behavior as soon as posible. Thk.

**Comment by pabloalmunia** [comment]
Please, try again, we are fixed this error.

**Comment by Hawmex** [comment]
Thanks. It works as expected. Closing.
