### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by anneb** [pabloalmunia/javacriptdecorators#8]
width = wideness of something
with = togetherness

file public/tutorial/lib/simple-decorator.js:
   width name => with name
file public/tutorial/lib/applied-order.js:
   width name => with name
file public/tutorial/lib/simple-log.js
  called width parameters => called with parameters
file public/tutorial/lib/simple-log-init.js
  called width parameters => called with parameters
file CHANGELOG.md
  create width => create with
file public/tutorial/index.html
  create the decorator width => create the decorator with

**Comment by pabloalmunia** [comment]
Thank you for identifying these errors, they have been fixed.
